title: "Introduction à l'apprentissage machine - GIF-4101 / GIF-7005"
name: "Université Laval"
email: christian.gagne@gel.ulaval.ca

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

plugins:
   - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      menu: main
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      sidebar:
        - title: "Introduction à l'apprentissage machine - GIF-4101 / GIF-7005"
          image: https://chgagne.github.io/iaa-ulaval/img/UL-logo.svg
          image_alt: "Université Laval"

include:
    - english.md
